# Generated by Django 5.2.13 on 2026-04-08 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Meeting',
        ),
    ]
